[package]
name = "rmq-listener"
version = "0.1.0"
edition = "2024"

[dependencies]
lapin = "2.3"
tokio = { version = "1.36", features = ["full"] }
tokio-amqp = "2.0"
futures-lite = "1.13"
dotenv = "0.15"
