services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - '5672:5672' # RabbitMQ default port
            - '15672:15672' # Management UI port
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
            - RABBITMQ_DEFAULT_VHOST=/
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

    rmq-listener:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - rabbitmq
        environment:
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USERNAME=guest
            - RABBITMQ_PASSWORD=guest
            - RABBITMQ_VHOST=/
            - RABBITMQ_EXCHANGE=common-domain
            - RABBITMQ_QUEUE=acme,test
        restart: unless-stopped

volumes:
    rabbitmq_data:
